#!/bin/sh

SELF_NAME=$0
VERSION=0.0
DESCRIPTION="Continuous integration"

BRANCH=master
PROJECT=acestream_search
STREAM=NBC
DEBUG=info

usage ()
{
    echo -e "
    $DESCRIPTION

    Usage:

    $SELF_NAME [-LvdVh] [-b BRANCH] [-r RELEASE] 
               [-p PROJECT] [-s STREAM]

    -b BRANCH
	    Git branch [$BRANCH]

    -r RELEASE
         Python version, Python version, repeat the option for multiple versions.

    -p PROJECT
         Project name [$PROJECT]

    -s STREAM
         Stream URL [$STREAM]

    -v
	    Verbose
    -d 
	    Debug
    -V
	    Version
    -h
	    Help
    "
    exit
}

OPTERR=0
while getopts b:r:p:vdVh OPTION; do
    case $OPTION in
	b)
	    BRANCH=$OPTARG
	    ;;
	r)
         MATRIX[${#MATRIX[*]}]=$OPTARG
	    ;;
	p)
	    PROJECT=$OPTARG
	    ;;
	v)
	    VERBOSE=" "
	    ;;
	d)
         DEBUG=debug
	    ;;
	V)
	    echo -e "
        $SELF_NAME $VERSION ${VERBOSE:+\\n\\t$DESCRIPTION\\n}\\n}
	    "
	    exit
	    ;;
	h|*)
	    usage
	    ;;
    esac
done
shift  $[$OPTIND - 1]


run_build () {

    [ "$DEBUG" = "debug" ] && set -x -v
    git archive --prefix=$PROJECT/ $BRANCH |
    docker run --rm -iv $VOLUME:/srv python:$RELEASE-slim tar ${VERBOSE:+v}xf - -C /srv

    echo "
    cd /srv/$PROJECT
    python --version
    python -c 'import struct; print(struct.calcsize(\"P\") * 8)'
    python -m pip install --disable-pip-version-check --user --upgrade pip setuptools

    python -m pip install pytest-cov
    python -m pip install -e .
    python -m pytest --cov
    python acestream_search -p terra.oz:7878 $STREAM 
    " |
    docker run --dns=172.27.1.11 --rm -iv $VOLUME:/srv python:$RELEASE-slim sh
    docker volume rm $VOLUME
}

[ ${#MATRIX[*]} -eq 0 ] &&
MATRIX=(2 3 3.5 3.6)

for RELEASE in ${MATRIX[@]}; do
    {
        VOLUME=${PROJECT}_${BRANCH}_${RELEASE}_$(date +%Y-%m-%d_%H-%M-%S)
        LOG=${VOLUME}.log
        SECONDS=0
        exec >> $LOG 2>&1 < /dev/null
        time run_build |
        while read LINE; do
            echo $(date "+%Y-%m-%d %H:%M:%S %z") $SECONDS $LINE 
        done
    } &
done
wait
